# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: check path
        run: ls -l

      - name: build app 
        run: docker build -t myapp:1.0.0 .

      - name: docker list
        run: docker images
      
      - name: deploy app
        run: | 
          if [ ! -z "$(docker ps |grep myapp)" ];then
              docker stop myapp
              docker rm myapp
              docker run -d --name myapp -p 8080:8080 myapp:1.0.0
          else
              docker run -d --name myapp -p 8080:8080 myapp:1.0.0
          fi
          sleep 60

      - name: test app
        run: curl localhost:8080